# macro file for the initialization of SimMACE in interactive session

# Set some default verbose
/control/verbose 2
/control/saveHistory
/run/verbose 2

# Initialize kernel
/run/initialize

# Customized properties
/MACE/Generator/SurfaceMuon/SetFlux                   1e7 s-1
/MACE/Generator/SurfaceMuon/SetRepetitionRate         50 Hz
/MACE/Generator/SurfaceMuon/SetTimeWidthRMS           100 us
/MACE/Generator/SurfaceMuon/SetEnergy                 1.5 MeV
/MACE/Generator/SurfaceMuon/SetEnergySpreadRMS        0.12 MeV
/MACE/Generator/SurfaceMuon/SetBeamProfileRMS         5 mm
/MACE/Generator/SurfaceMuon/SetVertexZ                -1.5 m
/MACE/Generator/SurfaceMuon/SetMuonsForEachG4Event    500

/MACE/Physics/MuoniumPhysics/Formation/SetFormationProbability     0.6
/MACE/Physics/MuoniumPhysics/Formation/SetConversionProbability    0.5    # very high :) 
/MACE/Physics/MuoniumPhysics/Transport/SetMeanFreePath             0.2 um
/MACE/Physics/MuoniumPhysics/Transport/SetTrialStepInVacuum        14 um

/MACE/Field/SetTransportMagneticField     0.1 tesla
/MACE/Field/SetAcceleratorPotential       7 kilovolt
/MACE/Field/SetSelectorElectricField      500 kilovolt/m

/MACE/Analysis/EnableCoincidenceOfEMCal   true
/MACE/Analysis/EnableCoincidenceOfMCP     true

# Name of output
/MACE/Analysis/SetResultName              SimMACE_result

# Visualization setting
/control/execute vis.mac
