# macro file for the test of SimTarget in batch session

# Set some default verbose
/control/verbose 0
/run/verbose 0

# I/O & Analysis
/MACE/Analysis/SetResultName                          SimTarget_result
/MACE/Analysis/EnableYieldAnalysis                    true

# Geometry
/MACE/Geometry/SetWorldHalfExtent                     25 25 25 cm
/MACE/Geometry/SetTargetWidth                         6 cm
/MACE/Geometry/SetTargetThickness                     1 cm
/MACE/Geometry/SetTargetDensity                       30 mg/cm3
/MACE/Geometry/SetTemperature                         293.15 K

# Initialize kernel
/run/initialize

# Muon beam properties
/MACE/Generator/SurfaceMuon/SetFlux                   1e7 s-1
/MACE/Generator/SurfaceMuon/SetRepetitionRate         50 Hz
/MACE/Generator/SurfaceMuon/SetTimeWidthRMS           100 us
/MACE/Generator/SurfaceMuon/SetEnergy                 1.5 MeV
/MACE/Generator/SurfaceMuon/SetEnergySpreadRMS        0.12 MeV
/MACE/Generator/SurfaceMuon/SetBeamProfileRMS         5 mm
/MACE/Generator/SurfaceMuon/SetVertexZ                -15 cm
/MACE/Generator/SurfaceMuon/SetMuonsForEachG4Event    1000

# Set physics
/MACE/Physics/MuoniumPhysics/Formation/SetFormationProbability     0.6
/MACE/Physics/MuoniumPhysics/Formation/SetConversionProbability    0
/MACE/Physics/MuoniumPhysics/Transport/SetMeanFreePath             0.2 um

# print progress
/run/printProgress 10

# kill secondaries
/MACE/Action/SetKillDecayProducts    true

# Run 0: Ablated target with pitch 15um, diameter 86um
/MACE/Physics/MuoniumPhysics/Transport/SetTrialStepInVacuum 14.9 um
/MACE/Geometry/SetFineStructure (z<-5 || x<-20||x>20 || y<-20||y>20) || ((x-(round((x-y/sqrt(3))/0.101)+round(2/sqrt(3)*y/0.101)/2)*0.101)^2+(y-sqrt(3)/2*round(2/sqrt(3)*y/0.101)*0.101)^2>0.086*0.086/4)
/run/beamOn 80
/mpi/status

# Run 1: Ablated target with pitch 25um, diameter 86um
/MACE/Physics/MuoniumPhysics/Transport/SetTrialStepInVacuum 24.9 um
/MACE/Geometry/SetFineStructure (z<-5 || x<-20||x>20 || y<-20||y>20) || ((x-(round((x-y/sqrt(3))/0.111)+round(2/sqrt(3)*y/0.111)/2)*0.111)^2+(y-sqrt(3)/2*round(2/sqrt(3)*y/0.111)*0.111)^2>0.086*0.086/4)
/run/beamOn 80
/mpi/status

# Run 2: Ablated target with pitch 15um, diameter 96um
/MACE/Physics/MuoniumPhysics/Transport/SetTrialStepInVacuum 14.9 um
/MACE/Geometry/SetFineStructure (z<-5 || x<-20||x>20 || y<-20||y>20) || ((x-(round((x-y/sqrt(3))/0.111)+round(2/sqrt(3)*y/0.111)/2)*0.111)^2+(y-sqrt(3)/2*round(2/sqrt(3)*y/0.111)*0.111)^2>0.096*0.096/4)
/run/beamOn 80
/mpi/status

# Enable result merge
/MACE/Analysis/EnableResultMerge true
