#############################################################################
#
# Macro file demo for SimMACE in batch session
#
#############################################################################

#############################################################################
# Initialization settings
#############################################################################

# Set some default verbose
/control/verbose 0
/run/verbose 0

# Initialize kernel
/run/initialize

# Customized properties
/MACE/Generator/SurfaceMuon/TimeRMS                0 ns
/MACE/Generator/SurfaceMuon/Momentum               28 MeV
/MACE/Generator/SurfaceMuon/MomentumRMS            0.7 MeV
/MACE/Generator/SurfaceMuon/PositionRMS            5 mm
/MACE/Generator/SurfaceMuon/PositionZ              -1.5 m
/MACE/Generator/SurfaceMuon/MuonsForEachG4Event    2000    # 50 kHz beam

/MACE/Physics/MuoniumPhysics/Formation/FormationProbability     0.6
/MACE/Physics/MuoniumPhysics/Formation/ConversionProbability    0
/MACE/Physics/MuoniumPhysics/Transport/MeanFreePath             0.2 um

/MACE/Field/AcceleratorPotential          5 kilovolt
/MACE/Field/SpectrometerMagneticField     0.1 tesla
/MACE/Field/SolenoidMagneticField         0.1 tesla

/MACE/Analysis/EnableCoincidenceOfEMCal   false
/MACE/Analysis/EnableCoincidenceOfMCP     false

#############################################################################
# Run
#############################################################################

/MACE/Analysis/FilePath   SimMACE_bkg
/MACE/Analysis/FileOption RECREATE
/run/beamOn 80
