/run/initialize

/MACE/PrimaryGenerator/SetFlux                   1e7 s-1
/MACE/PrimaryGenerator/SetRepetitionRate         50 Hz
/MACE/PrimaryGenerator/SetTimeWidthRMS           100 us
/MACE/PrimaryGenerator/SetEnergy                 1.5 MeV
/MACE/PrimaryGenerator/SetEnergySpreadRMS        0.08 MeV
/MACE/PrimaryGenerator/SetBeamProfileRMS         5 mm
/MACE/PrimaryGenerator/SetMuonsForEachG4Event    500

/MACE/Physics/SetConversionProbability           1.0          # high :) 

/MACE/Field/SetTransportMagneticField            0.1 tesla
/MACE/Field/SetAcceleratorPotential              7 kilovolt
/MACE/Field/SetSelectorElectricField             500 kilovolt/m

/MACE/Analysis/EnableCoincidenceOfCalorimeter    true
/MACE/Analysis/EnableCoincidenceOfVertexDetector true

/MACE/Analysis/SetResultName                     test

/run/printProgress 1
/run/beamOn 80
/mpi/status

/MACE/Analysis/MergeResult true
