/// @file Includes all fast geomerties.
/// @warning Don't overuse. Include only where needed.

#pragma once

#include "MACE/Detector/Geometry/Fast/BeamDegrader.hxx"
#include "MACE/Detector/Geometry/Fast/BeamMonitor.hxx"
#include "MACE/Detector/Geometry/Fast/CDCBody.hxx"
#include "MACE/Detector/Geometry/Fast/CDCCell.hxx"
#include "MACE/Detector/Geometry/Fast/CDCFieldWire.hxx"
#include "MACE/Detector/Geometry/Fast/CDCGas.hxx"
#include "MACE/Detector/Geometry/Fast/CDCSenseLayer.hxx"
#include "MACE/Detector/Geometry/Fast/CDCSenseWire.hxx"
#include "MACE/Detector/Geometry/Fast/CDCSuperLayer.hxx"
#include "MACE/Detector/Geometry/Fast/Collimator.hxx"
#include "MACE/Detector/Geometry/Fast/EMCal.hxx"
#include "MACE/Detector/Geometry/Fast/EMCalField.hxx"
#include "MACE/Detector/Geometry/Fast/EMCalShield.hxx"
#include "MACE/Detector/Geometry/Fast/FirstBendField.hxx"
#include "MACE/Detector/Geometry/Fast/FirstBendSolenoid.hxx"
#include "MACE/Detector/Geometry/Fast/FirstTransportField.hxx"
#include "MACE/Detector/Geometry/Fast/FirstTransportSolenoid.hxx"
#include "MACE/Detector/Geometry/Fast/LinacField.hxx"
#include "MACE/Detector/Geometry/Fast/MCP.hxx"
#include "MACE/Detector/Geometry/Fast/SecondBendField.hxx"
#include "MACE/Detector/Geometry/Fast/SecondBendSolenoid.hxx"
#include "MACE/Detector/Geometry/Fast/SecondTransportField.hxx"
#include "MACE/Detector/Geometry/Fast/SecondTransportSolenoid.hxx"
#include "MACE/Detector/Geometry/Fast/SelectorField.hxx"
#include "MACE/Detector/Geometry/Fast/SpectrometerField.hxx"
#include "MACE/Detector/Geometry/Fast/SpectrometerMagnet.hxx"
#include "MACE/Detector/Geometry/Fast/SpectrometerShield.hxx"
#include "MACE/Detector/Geometry/Fast/Target.hxx"
#include "MACE/Detector/Geometry/Fast/ThirdTransportField.hxx"
#include "MACE/Detector/Geometry/Fast/ThirdTransportSolenoid.hxx"
#include "MACE/Detector/Geometry/Fast/World.hxx"
