/// @file Includes all fast geomerties.
/// @warning Don't overuse. Include only where needed.

#pragma once

#include "MACE/Geometry/Entity/Fast/BeamDegrader.hxx"
#include "MACE/Geometry/Entity/Fast/BeamMonitor.hxx"
#include "MACE/Geometry/Entity/Fast/CDCBody.hxx"
#include "MACE/Geometry/Entity/Fast/CDCCell.hxx"
#include "MACE/Geometry/Entity/Fast/CDCFieldWire.hxx"
#include "MACE/Geometry/Entity/Fast/CDCGas.hxx"
#include "MACE/Geometry/Entity/Fast/CDCSenseLayer.hxx"
#include "MACE/Geometry/Entity/Fast/CDCSenseWire.hxx"
#include "MACE/Geometry/Entity/Fast/CDCSuperLayer.hxx"
#include "MACE/Geometry/Entity/Fast/Collimator.hxx"
#include "MACE/Geometry/Entity/Fast/EMCal.hxx"
#include "MACE/Geometry/Entity/Fast/EMCalField.hxx"
#include "MACE/Geometry/Entity/Fast/EMCalShield.hxx"
#include "MACE/Geometry/Entity/Fast/FirstBendField.hxx"
#include "MACE/Geometry/Entity/Fast/FirstBendSolenoid.hxx"
#include "MACE/Geometry/Entity/Fast/FirstTransportField.hxx"
#include "MACE/Geometry/Entity/Fast/FirstTransportSolenoid.hxx"
#include "MACE/Geometry/Entity/Fast/LinacField.hxx"
#include "MACE/Geometry/Entity/Fast/MCP.hxx"
#include "MACE/Geometry/Entity/Fast/SecondBendField.hxx"
#include "MACE/Geometry/Entity/Fast/SecondBendSolenoid.hxx"
#include "MACE/Geometry/Entity/Fast/SecondTransportField.hxx"
#include "MACE/Geometry/Entity/Fast/SecondTransportSolenoid.hxx"
#include "MACE/Geometry/Entity/Fast/SelectorField.hxx"
#include "MACE/Geometry/Entity/Fast/SpectrometerField.hxx"
#include "MACE/Geometry/Entity/Fast/SpectrometerMagnet.hxx"
#include "MACE/Geometry/Entity/Fast/SpectrometerShield.hxx"
#include "MACE/Geometry/Entity/Fast/Target.hxx"
#include "MACE/Geometry/Entity/Fast/ThirdTransportField.hxx"
#include "MACE/Geometry/Entity/Fast/ThirdTransportSolenoid.hxx"
#include "MACE/Geometry/Entity/Fast/World.hxx"
