#############################################################################
#
# Macro file demo for SimTarget in interactive session
#
#############################################################################

#############################################################################
# Initialization settings
#############################################################################

# Set some default verbose
/control/verbose 2
/control/saveHistory
/run/verbose 2

# I/O & Analysis
/MACE/Analysis/ResultPath                          SimTarget_result
/MACE/Analysis/EnableYieldAnalysis                    true

# Geometry
#/MACE/Geometry/Description/Import                     geom.yaml
/MACE/Geometry/TargetDensity                       30 mg/cm3
/MACE/Geometry/Temperature                         293.15 K

# Initialize kernel
/run/initialize

# Muon beam properties
/MACE/Generator/SurfaceMuon/Momentum               28 MeV
/MACE/Generator/SurfaceMuon/MomentumRMS            0.7 MeV
/MACE/Generator/SurfaceMuon/PositionRMS            5 mm
/MACE/Generator/SurfaceMuon/PositionZ                -5 cm
/MACE/Generator/SurfaceMuon/MuonsForEachG4Event    10

# Set physics
/MACE/Physics/MuoniumPhysics/Formation/FormationProbability     0.65
/MACE/Physics/MuoniumPhysics/Formation/ConversionProbability    0
/MACE/Physics/MuoniumPhysics/Transport/MeanFreePath             0.2 um

# print progress
/MPIRun/SetPrintProgress 1

# kill secondaries
/MACE/Action/KillIrrelevants    true

#############################################################################
# Visualization settings
#############################################################################

/vis/open OGL

/vis/viewer/set/autoRefresh false
/vis/verbose errors

/vis/drawVolume

/vis/viewer/set/viewpointVector -1 0.5 0.5
#/vis/viewer/set/lightsVector -1 1 1
#/vis/viewer/set/rotationStyle freeRotation
/vis/viewer/set/projection p
/vis/viewer/set/style s
/vis/viewer/set/auxiliaryEdge false
/vis/viewer/set/lineSegmentsPerCircle 100
/vis/viewer/zoom 10

# Colors
/vis/geometry/set/colour BeamMonitor     0     1     1     1     0.5
/vis/geometry/set/colour BeamDegrader    0     1     1     1     0.5
/vis/geometry/set/colour Target          0     1     1     1     0.5
/vis/geometry/set/colour World           0     1     1     1     0.01

/vis/scene/add/date
/vis/scene/add/axes 0 0 0 1 cm
/vis/scene/add/trajectories smooth #rich
/vis/scene/add/hits

/vis/filtering/trajectories/create/particleFilter
/vis/filtering/trajectories/particleFilter-0/add e+
/vis/filtering/trajectories/particleFilter-0/add e-
/vis/filtering/trajectories/particleFilter-0/add gamma
/vis/filtering/trajectories/particleFilter-0/add M
/vis/filtering/trajectories/particleFilter-0/add -M
/vis/filtering/trajectories/particleFilter-0/add mu+

/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/default/setDrawAuxPts false
/vis/modeling/trajectories/drawByParticleID-0/default/setAuxPtsSize 2
/vis/modeling/trajectories/drawByParticleID-0/default/setAuxPtsSizeType screen
/vis/modeling/trajectories/drawByParticleID-0/default/setAuxPtsType dots
/vis/modeling/trajectories/drawByParticleID-0/default/setDrawLine true
/vis/modeling/trajectories/drawByParticleID-0/default/setLineWidth 2
/vis/modeling/trajectories/drawByParticleID-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByParticleID-0/default/setStepPtsSize 2
/vis/modeling/trajectories/drawByParticleID-0/default/setStepPtsSizeType screen
/vis/modeling/trajectories/drawByParticleID-0/default/setStepPtsType dots

/vis/modeling/trajectories/drawByParticleID-0/setRGBA M 1 0 1 1
/vis/modeling/trajectories/drawByParticleID-0/setRGBA anti_M 1 0 1 1

/vis/scene/endOfEventAction accumulate

/vis/verbose warnings
/vis/viewer/set/autoRefresh true
