#############################################################################
# Initialization settings
#############################################################################

/control/verbose 0
/run/verbose 0

#/MACE/Detector/Description/Ixport mace_geom.yaml

/run/initialize

/gps/particle             mu+
/gps/direction            0 0 1        # 0 deg
/gps/pos/centre           0 0 -2 m     # 0 deg
/gps/pos/type             Beam
/gps/pos/shape            Circle
/gps/pos/radius           0 mm
/gps/pos/sigma_r          5 mm
/gps/ene/type             Gauss
/gps/ene/mono             3.647 MeV    # momentum 28 MeV
/gps/ene/sigma            0.1793 MeV   # momentum spreading 2.5%
/gps/number               10
/GPSX/PulseWidth          0 ns

/MACE/Physics/MuonDecay/IPPDecay/BR                      1
/MACE/Physics/MuonDecay/IPPDecay/MetropolisDelta         0.0025
/MACE/Physics/MuonDecay/IPPDecay/MetropolisDiscard       1000
/MACE/Physics/MuonDecay/IPPDecay/ApplyMACESpecificPxyCut true

/MACE/Physics/MuoniumPhysics/Formation/ConversionProbability    0

/MACE/Field/AcceleratorPotential          500 volt
/MACE/Field/MMSMagneticField              0.1 tesla
/MACE/Field/SolenoidMagneticField         0.1 tesla
/MACE/Field/EMCMagneticField              0.1 tesla

/MACE/Analysis/CoincidenceWithCDC     true
/MACE/Analysis/CoincidenceWithSTC     true
/MACE/Analysis/CoincidenceWithMCP     true
/MACE/Analysis/CoincidenceWithEMC     true

#############################################################################
# Run
#############################################################################

/MACE/Analysis/FilePath SimMACE_mu2eeevv
/MACE/Analysis/FileMode NEW
/run/beamOn 1000000
/MPIRun/PrintRunSummary
