#############################################################################
# Initialization settings
#############################################################################

/control/verbose 0
/run/verbose 0

/run/initialize

/gps/particle                                  mu+
/gps/direction                                 0 0 1
/gps/pos/type                                  Beam
/gps/pos/shape                                 Circle
/gps/pos/centre                                0 0 -1.5 m
/gps/pos/radius                                0 mm
/gps/pos/sigma_r                               5 mm
/gps/ene/type                                  Gauss
/gps/ene/mono                                  3.647 MeV    # momentum 28 MeV
/gps/ene/sigma                                 0.1793 MeV
/MACE/Generator/GPS/PulseWidth                 0 ns
/MACE/Generator/GPS/PrimariesForEachG4Event    10

/MACE/Physics/MuonDecay/IPPDecay/BR                   1
/MACE/Physics/MuonDecay/IPPDecay/MetropolisDelta      0.005
/MACE/Physics/MuonDecay/IPPDecay/MetropolisDiscard    1000
/MACE/Physics/MuonDecay/IPPDecay/ApplyMACESpecificCut true

/MACE/Physics/MuoniumPhysics/Formation/FormationProbability     0.655
/MACE/Physics/MuoniumPhysics/Formation/ConversionProbability    0
/MACE/Physics/MuoniumPhysics/Transport/MeanFreePath             0.2 um

/MACE/Field/AcceleratorPotential          5 kilovolt
/MACE/Field/SpectrometerMagneticField     0.1 tesla
/MACE/Field/SolenoidMagneticField         0.1 tesla
/MACE/Field/EMCMagneticField              0.1 tesla

/MACE/Analysis/CoincidenceWithCDC     true
/MACE/Analysis/CoincidenceWithMCP     true
/MACE/Analysis/CoincidenceWithEMC     true

#############################################################################
# Run
#############################################################################

/MACE/Analysis/FilePath   SimMACE_mu2eeevv
/MACE/Analysis/FileOption NEW
/run/beamOn 1000000
/MPIRun/PrintRunSummary
