#############################################################################
# Initialization settings
#############################################################################

/control/verbose 0
/run/verbose 0

#/MACE/Detector/Description/Ixport SimMACE_geom.yaml

/run/initialize

/gps/particle             neutron
/gps/pos/type             Volume
/gps/pos/shape            Para
/gps/pos/centre           2 0 0 m
/gps/pos/halfx            1 m
/gps/pos/halfy            1 m
/gps/pos/halfz            1 m
/gps/ang/type             iso
/gps/ene/type             Lin
/gps/ene/gradient         0
/gps/ene/intercept        1
/gps/ene/min              0.025 eV
/gps/ene/max              5 MeV
/GPSX/NVertex             1000
/GPSX/PulseWidth          0 ns

/MACE/Analysis/SavePrimaryVertexData  false
/MACE/Analysis/SaveDecayVertexData    false
/MACE/Analysis/CoincidenceWithCDC     false
/MACE/Analysis/CoincidenceWithTTC     false
/MACE/Analysis/CoincidenceWithMMS     false
/MACE/Analysis/CoincidenceWithMCP     false
/MACE/Analysis/CoincidenceWithEMC     false

#############################################################################
# Run
#############################################################################

/MACE/Analysis/FilePath SimMACE_env_neutron
/MACE/Analysis/FileMode NEW
/run/beamOn 80
/Mustard/Run/PrintRunSummary
