#############################################################################
#
# Macro file demo for SimMACE in batch session
#
#############################################################################

#############################################################################
# Initialization settings
#############################################################################

# Set some default verbose
/control/verbose 0
/run/verbose 0

# Initialize kernel
/run/initialize

# Customized properties
/MACE/Generator/SurfaceMuon/PulseWidth                0 ns
/MACE/Generator/SurfaceMuon/Momentum               28 MeV
/MACE/Generator/SurfaceMuon/MomentumRMS            0.7 MeV
/MACE/Generator/SurfaceMuon/PositionRMS            5 mm
/MACE/Generator/SurfaceMuon/PositionZ              -1.5 m
/MACE/Generator/SurfaceMuon/PrimariesForEachG4Event    1

/MACE/Physics/MuoniumPhysics/Formation/FormationProbability     1
/MACE/Physics/MuoniumPhysics/Formation/ConversionProbability    1
/MACE/Physics/MuoniumPhysics/Transport/MeanFreePath             0.2 um

/MACE/Field/AcceleratorPotential          5 kilovolt
/MACE/Field/SpectrometerMagneticField     0.1 tesla
/MACE/Field/SolenoidMagneticField         0.1 tesla

/MACE/Analysis/CoincidenceWithCDC     true
/MACE/Analysis/CoincidenceWithMCP     true
/MACE/Analysis/CoincidenceWithEMC     true

#############################################################################
# Run
#############################################################################

#/MPIRun/PrintProgressModulo 100

/MACE/Analysis/FilePath   SimMACE_sig
/MACE/Analysis/FileOption RECREATE
/run/beamOn 8000
/MPIRun/PrintRunSummary
