#############################################################################
# Initialization settings
#############################################################################

/control/verbose 0
/run/verbose 0

#/MACE/Detector/Description/Ixport SimMACE_geom.yaml

/run/initialize

/gps/particle             mu+
/gps/direction            0 0 1        # 0 deg
/gps/pos/centre           0 0 -2 m     # 0 deg
/gps/pos/type             Beam
/gps/pos/shape            Circle
/gps/pos/radius           0 mm
/gps/pos/sigma_r          5 mm
/gps/ene/type             Gauss
/gps/ene/mono             3.647 MeV    # momentum 28 MeV
/gps/ene/sigma            0.1793 MeV   # momentum spreading 2.5%
/GPSX/NVertex             10
/GPSX/PulseWidth          1.5 us

/Mustard/Physics/MuonDecay/IPPDecay/BR                      1
/Mustard/Physics/MuonDecay/IPPDecay/MetropolisDelta         0.005
/Mustard/Physics/MuonDecay/IPPDecay/MetropolisDiscard       1000
/Mustard/Physics/MuonDecay/RadiativeDecay/BR                0
/Mustard/Physics/MuonDecay/UpdateDecayBR

/Mustard/Physics/MuoniumPhysics/Formation/ConversionProbability    0

/MACE/Analysis/CoincidenceWithCDC     true
/MACE/Analysis/CoincidenceWithTTC     true
/MACE/Analysis/CoincidenceWithMMS     true
/MACE/Analysis/CoincidenceWithMCP     true
/MACE/Analysis/CoincidenceWithEMC     true

#############################################################################
# Run
#############################################################################

/MACE/Analysis/FilePath SimMACE_mu2eeevv
/MACE/Analysis/FileMode NEW
/run/beamOn 1000000
/Mustard/Run/PrintRunSummary
