#############################################################################
# Initialization settings
#############################################################################

/control/verbose 0
/run/verbose 0

#/Mustard/Detector/Description/Ixport SimMACE_geom.yaml

/run/initialize




/Mustard/Physics/MuoniumPhysics/Formation/ConversionProbability    0

/MACE/Physics/ApplyProductionCutNearTarget                         no

/MACE/Analysis/SavePrimaryVertexData  no
/MACE/Analysis/SaveDecayVertexData    yes
/MACE/Analysis/CoincidenceWithMMS     no
/MACE/Analysis/CoincidenceWithMCP     no
/MACE/Analysis/CoincidenceWithECAL    no
/MACE/Analysis/SaveTTCHitData         no
/MACE/Analysis/SaveCDCHitData         no

#############################################################################
# Run
#############################################################################

/Mustard/Analysis/FilePath SimMACE_beam_ep
/Mustard/Analysis/FileMode NEW
/run/beamOn 1000
/Mustard/Run/PrintRunSummary
