#############################################################################
# Initialization settings
#############################################################################

/control/verbose 2
#/control/saveHistory
/run/verbose 2

#/Mustard/Detector/Description/Export SimVeto_geom.yaml
/Mustard/Detector/Description/Import SimVeto_geom.yaml
#/Mustard/Detector/Description/Ixport SimVeto_geom.yaml

/MACE/Physics/UseOpticalPhysics


/run/initialize

/MACE/Generator/SwitchToGPSX
/GPSX/NVertex             1
/GPSX/PulseWidth          0 ns
/gps/particle             opticalphoton
/gps/pos/centre           690.2 -751 699.6 mm
/gps/ang/type             iso
/gps/ang/maxtheta         360 deg
/gps/ene/mono             2.6 eV




/Mustard/Physics/MuoniumPhysics/Formation/ConversionProbability    0.5

/MACE/Analysis/FilePath SimVeto_wsl_test
/MACE/Analysis/FileMode RECREATE

/run/beamOn 10000
