#############################################################################
# Initialization settings
#############################################################################

/control/verbose 2
#/control/saveHistory
/run/verbose 2

#/Mustard/Detector/Description/Export SimVeto_geom.yaml
/Mustard/Detector/Description/Import SimVeto_geom.yaml
#/Mustard/Detector/Description/Ixport SimVeto_geom.yaml

/MACE/Physics/UseOpticalPhysics


/run/initialize

/MACE/Generator/SwitchToGPSX
/GPSX/NVertex             1
/GPSX/PulseWidth          0 ns
/gps/particle             proton
/gps/pos/centre           0 0 0 mm
/gps/direction            690.2 -763.5 0
/gps/ene/mono             120 GeV

/Mustard/Physics/MuoniumPhysics/Formation/ConversionProbability    0.5

/MACE/Analysis/FilePath SimVeto_untitled
/MACE/Analysis/FileMode RECREATE

#############################################################################
# Visualization settings
#############################################################################

/vis/open OGL

/vis/viewer/set/autoRefresh no
/vis/verbose errors

/vis/drawVolume

/vis/viewer/set/viewpointVector -1 0 0
/vis/viewer/set/lightsVector -1 1 1
#/vis/viewer/set/rotationStyle freeRotation
/vis/viewer/set/projection p
/vis/viewer/set/style s
/vis/viewer/set/auxiliaryEdge no
#/vis/viewer/set/lineSegmentsPerCircle 100
/vis/viewer/zoom 2.5

# Visibility

/vis/geometry/set/visibility World                         0          no
# remove all virtrual geometry in veto
/vis/geometry/set/visibility VetoModuleBox_0                 0          no
/vis/geometry/set/visibility VetoModuleBox_1                 0          no
/vis/geometry/set/visibility VetoModuleBox_2                 0          no
/vis/geometry/set/visibility VetoModuleBox_3                 0          no

# Colors
/vis/geometry/set/colour VetoFiberHole_0                       0     1     1     1       0.
/vis/geometry/set/colour VetoFiberHole_1                       0     1     1     1       0.
/vis/geometry/set/colour VetoFiberHole_2                       0     1     1     1       0.
/vis/geometry/set/colour VetoFiberHole_3                       0     1     1     1       0.
/vis/geometry/set/colour VetoFiberOuter_0                      0     0     1     0       0.1
/vis/geometry/set/colour VetoFiberInner_0                      0     0     1     0       0.2
/vis/geometry/set/colour VetoFiberCore_0                       0     0     1     0       0.3
/vis/geometry/set/colour VetoFiberOuter_1                      0     0     1     0       0.1
/vis/geometry/set/colour VetoFiberInner_1                      0     0     1     0       0.2
/vis/geometry/set/colour VetoFiberCore_1                       0     0     1     0       0.3
/vis/geometry/set/colour VetoFiberOuter_2                      0     0     1     0       0.1
/vis/geometry/set/colour VetoFiberInner_2                      0     0     1     0       0.2
/vis/geometry/set/colour VetoFiberCore_2                       0     0     1     0       0.3
/vis/geometry/set/colour VetoFiberOuter_3                      0     0     1     0       0.1
/vis/geometry/set/colour VetoFiberInner_3                      0     0     1     0       0.2
/vis/geometry/set/colour VetoFiberCore_3                       0     0     1     0       0.3
/vis/geometry/set/colour VetoStrip_0                           0     1     0     0       0.2
/vis/geometry/set/colour VetoStrip_1                           0     0     0     1       0.2
/vis/geometry/set/colour VetoStrip_2                           0     0     1     0       0.2
/vis/geometry/set/colour VetoStrip_3                           0     0.7   0     0.3     0.2
/vis/geometry/set/colour VetoStripBox_0                        0     1     0     0       0.05
/vis/geometry/set/colour VetoStripBox_1                        0     0     0     1       0.05
/vis/geometry/set/colour VetoStripBox_2                        0     0     1     0       0.05
/vis/geometry/set/colour VetoStripBox_3                        0     0.7   0     0.3     0.05
/vis/geometry/set/colour VetoAlAbsorber_0                      0     1     1     1       0.3
/vis/geometry/set/colour VetoAlAbsorber_1                      0     1     1     1       0.3
/vis/geometry/set/colour VetoAlAbsorber_2                      0     1     1     1       0.3
/vis/geometry/set/colour VetoAlAbsorber_3                      0     1     1     1       0.3
/vis/geometry/set/colour VetoSiPMCoupler                       0     1     1     1       0.2
/vis/geometry/set/colour VetoSiPM                              0     1     1     1       0.1
/vis/geometry/set/colour VetoCathode                           0     1     1     1       0.3

/vis/scene/add/date
/vis/scene/add/axes 0 0 0 10 cm
/vis/scene/add/trajectories smooth #rich
/vis/scene/add/hits
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/default/setDrawAuxPts no
/vis/modeling/trajectories/drawByParticleID-0/default/setAuxPtsSize 2
/vis/modeling/trajectories/drawByParticleID-0/default/setAuxPtsSizeType screen
/vis/modeling/trajectories/drawByParticleID-0/default/setAuxPtsType dots
/vis/modeling/trajectories/drawByParticleID-0/default/setDrawLine yes
/vis/modeling/trajectories/drawByParticleID-0/default/setLineWidth 2
/vis/modeling/trajectories/drawByParticleID-0/default/setDrawStepPts yes
/vis/modeling/trajectories/drawByParticleID-0/default/setStepPtsSize 2
/vis/modeling/trajectories/drawByParticleID-0/default/setStepPtsSizeType screen
/vis/modeling/trajectories/drawByParticleID-0/default/setStepPtsType dots

/vis/modeling/trajectories/drawByParticleID-0/setRGBA muonium 1 0 1 1
/vis/modeling/trajectories/drawByParticleID-0/setRGBA anti_muonium 1 0 1 1

/vis/scene/endOfEventAction accumulate

/vis/verbose warnings
/vis/viewer/set/autoRefresh yes
