#############################################################################
# Initialization settings
#############################################################################

/control/verbose 2
#/control/saveHistory
/run/verbose 2

#/Mustard/Detector/Description/Ixport SimVeto_geom.yaml

/run/initialize

/Mustard/EcoMug/Position/HSphere 0 0 0 m
/Mustard/EcoMug/Size/HSphere/Radius 2 m

/MACE/Analysis/FilePath SimVeto_untitled
/MACE/Analysis/FileMode RECREATE

#############################################################################
# Visualization settings
#############################################################################

/vis/open OGL

/vis/viewer/set/autoRefresh no
/vis/verbose errors

/vis/drawVolume

/vis/viewer/set/viewpointVector -1 0.5 0.5
/vis/viewer/set/lightsVector -1 1 1
#/vis/viewer/set/rotationStyle freeRotation
/vis/viewer/set/projection p
/vis/viewer/set/style s
/vis/viewer/set/auxiliaryEdge no
#/vis/viewer/set/lineSegmentsPerCircle 100
/vis/viewer/zoom 2.5

# Visibility

/vis/geometry/set/visibility World                         0          no

# remove all virtrual geometry in veto
/vis/geometry/set/visibility VetoModuleBox_0                 0          no
/vis/geometry/set/visibility VetoModuleBox_1                 0          no
/vis/geometry/set/visibility VetoModuleBox_2                 0          no
/vis/geometry/set/visibility VetoModuleBox_3                 0          no

# Colors
/vis/geometry/set/colour VetoFiberHole_0                       0     1     1     1       0.
/vis/geometry/set/colour VetoFiberHole_1                       0     1     1     1       0.
/vis/geometry/set/colour VetoFiberHole_2                       0     1     1     1       0.
/vis/geometry/set/colour VetoFiberHole_3                       0     1     1     1       0.
/vis/geometry/set/colour VetoFiberOuter_0                      0     0     1     0       0.1
/vis/geometry/set/colour VetoFiberInner_0                      0     0     1     0       0.2
/vis/geometry/set/colour VetoFiberCore_0                       0     0     1     0       0.3
/vis/geometry/set/colour VetoFiberOuter_1                      0     0     1     0       0.1
/vis/geometry/set/colour VetoFiberInner_1                      0     0     1     0       0.2
/vis/geometry/set/colour VetoFiberCore_1                       0     0     1     0       0.3
/vis/geometry/set/colour VetoFiberOuter_2                      0     0     1     0       0.1
/vis/geometry/set/colour VetoFiberInner_2                      0     0     1     0       0.2
/vis/geometry/set/colour VetoFiberCore_2                       0     0     1     0       0.3
/vis/geometry/set/colour VetoFiberOuter_3                      0     0     1     0       0.1
/vis/geometry/set/colour VetoFiberInner_3                      0     0     1     0       0.2
/vis/geometry/set/colour VetoFiberCore_3                       0     0     1     0       0.3
/vis/geometry/set/colour VetoStrip_0                           0     1     0     0       0.2
/vis/geometry/set/colour VetoStrip_1                           0     0     0     1       0.2
/vis/geometry/set/colour VetoStrip_2                           0     0     1     0       0.2
/vis/geometry/set/colour VetoStrip_3                           0     0.7   0     0.3     0.2
/vis/geometry/set/colour VetoStripBox_0                        0     1     0     0       0.05
/vis/geometry/set/colour VetoStripBox_1                        0     0     0     1       0.05
/vis/geometry/set/colour VetoStripBox_2                        0     0     1     0       0.05
/vis/geometry/set/colour VetoStripBox_3                        0     0.7   0     0.3     0.05
/vis/geometry/set/colour VetoAlAbsorber_0                      0     1     1     1       0.3
/vis/geometry/set/colour VetoAlAbsorber_1                      0     1     1     1       0.3
/vis/geometry/set/colour VetoAlAbsorber_2                      0     1     1     1       0.3
/vis/geometry/set/colour VetoAlAbsorber_3                      0     1     1     1       0.3
/vis/geometry/set/colour VetoSiPMCoupler                       0     1     1     1       0.2
/vis/geometry/set/colour VetoSiPM                              0     1     1     1       0.1
/vis/geometry/set/colour VetoCathode                           0     1     1     1       0.3


/vis/scene/add/date
/vis/scene/add/axes 0 0 0 1 m
/vis/scene/add/trajectories smooth #rich
/vis/scene/add/hits

/vis/filtering/trajectories/create/particleFilter
/vis/filtering/trajectories/particleFilter-0/add mu+
/vis/filtering/trajectories/particleFilter-0/add mu-
/vis/filtering/trajectories/particleFilter-0/add muonium
/vis/filtering/trajectories/particleFilter-0/add anti_muonium
/vis/filtering/trajectories/particleFilter-0/add e+
/vis/filtering/trajectories/particleFilter-0/add e-
/vis/filtering/trajectories/particleFilter-0/add gamma
/vis/filtering/trajectories/particleFilter-0/add opticalphoton
/vis/filtering/trajectories/particleFilter-0/add neutron
/vis/filtering/trajectories/particleFilter-0/add anti_neutron
/vis/filtering/trajectories/particleFilter-0/add proton
/vis/filtering/trajectories/particleFilter-0/add anti_proton
/vis/filtering/trajectories/particleFilter-0/add pi+
/vis/filtering/trajectories/particleFilter-0/add pi-
/vis/filtering/trajectories/particleFilter-0/add pi0

/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/default/setDrawAuxPts no
/vis/modeling/trajectories/drawByParticleID-0/default/setAuxPtsSize 2
/vis/modeling/trajectories/drawByParticleID-0/default/setAuxPtsSizeType screen
/vis/modeling/trajectories/drawByParticleID-0/default/setAuxPtsType dots
/vis/modeling/trajectories/drawByParticleID-0/default/setDrawLine yes
/vis/modeling/trajectories/drawByParticleID-0/default/setLineWidth 2
/vis/modeling/trajectories/drawByParticleID-0/default/setDrawStepPts yes
/vis/modeling/trajectories/drawByParticleID-0/default/setStepPtsSize 2
/vis/modeling/trajectories/drawByParticleID-0/default/setStepPtsSizeType screen
/vis/modeling/trajectories/drawByParticleID-0/default/setStepPtsType dots

/vis/modeling/trajectories/drawByParticleID-0/setRGBA muonium 1 0 1 1
/vis/modeling/trajectories/drawByParticleID-0/setRGBA anti_muonium 1 0 1 1

/vis/scene/endOfEventAction accumulate

/vis/verbose warnings
/vis/viewer/set/autoRefresh yes
