#pragma once

#define MACE_VERSION_WORLD 0
#define MACE_VERSION_MAJOR 0
#define MACE_VERSION_MINOR 0

#define MACE_VERSION_STRING_HELPER1(world, major, minor) world.major.minor
#define MACE_VERSION_STRING_HELPER2(version) #version
#define MACE_VERSION_STRING_HELPER3(version) MACE_VERSION_STRING_HELPER2(version)
#define MACE_VERSION_STRING \
    MACE_VERSION_STRING_HELPER3(MACE_VERSION_STRING_HELPER1(MACE_VERSION_WORLD, MACE_VERSION_MAJOR, MACE_VERSION_MINOR))
