message(STATUS "Configuring built-in yaml-cpp")

# set(CMAKE_INSTALL_PREFIX_STORE "${CMAKE_INSTALL_PREFIX}")
# set(CMAKE_INSTALL_PREFIX "${CMAKE_")
# set(CMAKE_CXX_STANDARD_STORE)

set(YAML_BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)
set(YAML_CPP_INSTALL OFF CACHE BOOL "" FORCE)
if(MACE_USE_SHARED_MSVC_RT)
    set(YAML_MSVC_SHARED_RT ON CACHE BOOL "" FORCE)
else()
    set(YAML_MSVC_SHARED_RT OFF CACHE BOOL "" FORCE)
endif()

add_subdirectory(${MACE_BUILTIN_YAML_CPP_DIR})

# set(CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX_STORE}")
# unset(CMAKE_CXX_STANDARD_STORE)
# set(CMAKE_CXX_STANDARD ${CMAKE_CXX_STANDARD_STORE})
# unset(CMAKE_INSTALL_PREFIX_STORE)

message(STATUS "Configuring built-in yaml-cpp - done")
