if(NOT MACE_BUILDIN_YAML_CPP)
    find_package(yaml-cpp 0.6.0 QUIET)
    if(NOT yaml-cpp_FOUND)
        message(NOTICE "***Notice: yaml-cpp not found. Turning on MACE_BUILDIN_YAML_CPP")
        set(MACE_BUILDIN_YAML_CPP ON)
        set(YAML_CPP_INCLUDE_DIR ${MACE_BUILDIN_YAML_CPP_DIR}/include)
        set(YAML_CPP_LIBRARIES yaml-cpp)
    endif()
endif()
message(STATUS "MACE will use yaml-cpp headers from: ${YAML_CPP_INCLUDE_DIR}")
message(STATUS "MACE will use yaml-cpp libraries: ${YAML_CPP_LIBRARIES}")
