#############################################################################
#
# Macro file demo for SimMACE in batch session
#
#############################################################################

#############################################################################
# Initialization settings
#############################################################################

# Set some default verbose
/control/verbose 0
/run/verbose 0

# Initialize kernel
/run/initialize

# Customized properties
/gps/source/intensity 1
/gps/particle gamma
/gps/pos/type Volume
/gps/pos/shape Para
/gps/pos/centre 3 0 0 m
/gps/pos/halfx 1 m
/gps/pos/halfy 1 m
/gps/pos/halfz 1 m
/gps/ang/type iso
/gps/ene/type Lin
/gps/ene/min 1. MeV
/gps/ene/max 5. MeV

/gps/source/add 1
/gps/particle neutron
/gps/pos/type Volume
/gps/pos/shape Para
/gps/pos/centre 3 0 0 m
/gps/pos/halfx 1 m
/gps/pos/halfy 1 m
/gps/pos/halfz 1 m
/gps/ang/type iso
/gps/ene/type Lin
/gps/ene/min 1. MeV
/gps/ene/max 5. MeV

#############################################################################
# Run
#############################################################################

/MACE/Analysis/FilePath   SimMACE_bkg
/MACE/Analysis/FileOption RECREATE
/run/beamOn 80
/MPIRun/PrintRunSummary