/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0

/MACE/Physics/UseOpticalPhysics
#/MACE/Detector/Description/Import test.yaml

/run/initialize

/MACE/Generator/SwitchToGPSX

/gps/particle gamma
/gps/ene/mono 0.511 MeV
/gps/pos/centre 0. 0. 0. cm
/gps/direction 0.386541 0.231259 0.883817

/MACE/Analysis/FilePath test
/MACE/Analysis/FileMode RECREATE
/run/beamOn 5000
/MPIRun/PrintRunSummary
