/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0

/MACE/Generator/SwitchToGPS
#/MACE/Physics/UseOpticalPhysics

/run/initialize

/gps/source/intensity 1
/gps/particle ion
/gps/ion 11 22
/gps/ene/mono 0. MeV
/gps/pos/centre 0. 0. 0. cm

/gps/source/add 1
/gps/particle ion
/gps/ion 55 137
/gps/ene/mono 0. MeV
/gps/pos/centre 0. 0. 0. cm

/gps/source/add 1
/gps/particle ion
/gps/ion 63 152
/gps/ene/mono 0. MeV
/gps/pos/centre 0. 0. 0. cm

/MACE/Analysis/FilePath   SimEMC_source
/MACE/Analysis/FileOption RECREATE
/run/beamOn 1000
/MPIRun/PrintRunSummary
