name: Static code analysis (AMD64 GNU/Linux Clang, ClangFormat, ClangTidy)

on:
  push:
    branches: ["**"]
    paths:
      - "src/**"
      - "MACE.c\\+\\+"
      - "**/CMakeLists.txt"
      - "**.cmake"
      - ".clang-format"
      - ".clang-tidy"
  pull_request:
    branches: ["**"]
    paths:
      - "src/**"
      - "MACE.c\\+\\+"
      - "**/CMakeLists.txt"
      - "**.cmake"
      - ".clang-format"
      - ".clang-tidy"

jobs:
  clang-format-tidy:
    name: Clang, ClangFormat, ClangTidy
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - url: ghcr.io/zhao-shihan/rgb-docker
    container: ${{ matrix.image.url }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Static code analysis
        run: |
          . /environment
          mkdir build && cd build
          cmake -G Ninja .. \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_C_COMPILER=clang \
            -DCMAKE_CXX_COMPILER=clang++ \
            -DCMAKE_C_FLAGS='-Werror -march=native' \
            -DCMAKE_CXX_FLAGS='-Werror -march=native' \
            -DMACESW_CLANG_FORMAT \
            -DMACESW_CLANG_FORMAT_WERROR \
            -DMACESW_CLANG_TIDY \
            -DMACESW_CLANG_TIDY_WERROR
          ninja
