/// @file Includes all fast geomerties.
/// @warning Don't overuse. Include only where needed. Otherwise it will definitely prolong the compilation time.

#pragma once

#include "MACE/Core/Geometry/Entity/Fast/BeamCounter.hxx"
#include "MACE/Core/Geometry/Entity/Fast/BeamDegrader.hxx"
#include "MACE/Core/Geometry/Entity/Fast/CDCBody.hxx"
#include "MACE/Core/Geometry/Entity/Fast/CDCCell.hxx"
#include "MACE/Core/Geometry/Entity/Fast/CDCFieldWire.hxx"
#include "MACE/Core/Geometry/Entity/Fast/CDCLayer.hxx"
#include "MACE/Core/Geometry/Entity/Fast/CDCSenseWire.hxx"
#include "MACE/Core/Geometry/Entity/Fast/CDCSensitiveVolume.hxx"
#include "MACE/Core/Geometry/Entity/Fast/Collimator.hxx"
#include "MACE/Core/Geometry/Entity/Fast/EMCal.hxx"
#include "MACE/Core/Geometry/Entity/Fast/EMCalField.hxx"
#include "MACE/Core/Geometry/Entity/Fast/EMCalShield.hxx"
#include "MACE/Core/Geometry/Entity/Fast/FirstBendField.hxx"
#include "MACE/Core/Geometry/Entity/Fast/FirstBendSolenoid.hxx"
#include "MACE/Core/Geometry/Entity/Fast/FirstTransportField.hxx"
#include "MACE/Core/Geometry/Entity/Fast/FirstTransportSolenoid.hxx"
#include "MACE/Core/Geometry/Entity/Fast/LinacField.hxx"
#include "MACE/Core/Geometry/Entity/Fast/MCP.hxx"
#include "MACE/Core/Geometry/Entity/Fast/SecondBendField.hxx"
#include "MACE/Core/Geometry/Entity/Fast/SecondBendSolenoid.hxx"
#include "MACE/Core/Geometry/Entity/Fast/SecondTransportField.hxx"
#include "MACE/Core/Geometry/Entity/Fast/SecondTransportSolenoid.hxx"
#include "MACE/Core/Geometry/Entity/Fast/SelectorField.hxx"
#include "MACE/Core/Geometry/Entity/Fast/SpectrometerField.hxx"
#include "MACE/Core/Geometry/Entity/Fast/SpectrometerMagnet.hxx"
#include "MACE/Core/Geometry/Entity/Fast/SpectrometerShield.hxx"
#include "MACE/Core/Geometry/Entity/Fast/Target.hxx"
#include "MACE/Core/Geometry/Entity/Fast/ThirdTransportField.hxx"
#include "MACE/Core/Geometry/Entity/Fast/ThirdTransportSolenoid.hxx"
#include "MACE/Core/Geometry/Entity/Fast/World.hxx"
